apiVersion: apps/v1
kind: Deployment
metadata:
  name: emailing-depl
spec:
  replicas: 1
  selector:
    matchLabels:
      app: emailing
  template:
    metadata:
      labels:
        app: emailing
    spec:
      containers:
        - name: emailing
          image: jerry377/emailing
          env:
            - name: MONGO_URI
              value: 'mongodb://auth-mongo-srv:27017/asfuth'
            - name: JWT_KEY
              valueFrom:
                secretKeyRef:
                  name: jwt-secret
                  key: JWT_KEY
