name: tests-kms

on:
  pull_request:
    paths:
      - 'kms/**'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: cd kms && npm install && npm run test:ci
      
